version: '3'
services:
  lb:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    volumes:
      - ./nginx/:/usr/share/nginx/html/
    ports:
      - "9090:9090"
    depends_on:
      - service1
      - service2
      - service3
  service1:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./nginx/:/usr/share/nginx/html/
    ports:
      - "8181:8080"
  service2:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./nginx/:/usr/share/nginx/html/
    ports:
      - "8282:8080"
  service3:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./nginx/:/usr/share/nginx/html/
    ports:
      - "8383:8080"
