version: '3'
services:
  influxdbintegrationtests:
    image: influxdb:2.0
    container_name: integration-influxdb
    volumes:
      - ./influxdb/data:/var/lib/influxdb2
      - ./influxdb/config:/etc/influxdb2
      - ./influxdb/scripts:/docker-entrypoint-initdb.d
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=${INFLUXDB_USR}
      - DOCKER_INFLUXDB_INIT_PASSWORD=${INFLUXDB_PWD}
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=${INFLUXDB_TOK}
      - DOCKER_INFLUXDB_INIT_ORG=subjects
      - DOCKER_INFLUXDB_INIT_BUCKET=testUser
    env_file:
      - .env
    ports:
      - ${INFLUXDB_PORT}:8086

  postgres:
    image: postgres:latest
    container_name: integration-postgres
    volumes:
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - ${POSTGRES_PORT}:5432
