# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
#   runDBs:
#     The type of runner that the job will run on
#     runs-on: ubuntu-latest

#     Steps represent a sequence of tasks that will be executed as part of the job
#     steps:
#       Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
#       - uses: actions/checkout@v2
        
#       - name: Runs docker using make
#         working-directory: ./lab01/fdserver/integrationTest
#         run: make run
        
  runUnitTests:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b
      - name: Run tests with gradle
        working-directory: ./lab01/fdserver
        run: sudo ./gradlew unitTest --rerun-tasks
        
  runIntegrationTests:
    needs: runUnitTests
    runs-on: ubuntu-latest
    
#     services:
#       influxdbintegrationtests:
#         image: influxdb:2.0
#         volumes:
#           - /lab01/fdserver/integrationTest/influxdb/data:/var/lib/influxdb2
#           - /lab01/fdserver/integrationTest/influxdb/config:/etc/influxdb2
#           - /lab01/fdserver/integrationTest/influxdb/scripts:/docker-entrypoint-initdb.d
#         env:
#           DOCKER_INFLUXDB_INIT_MODE: setup
#           DOCKER_INFLUXDB_INIT_USERNAME: admin
#           DOCKER_INFLUXDB_INIT_PASSWORD: password
#           DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: HsJBf0sINtvxedXJio2Lg7iskJgLcR5q8a0MZtqoiWZt66pBEQ0LUz0IPEe5ooD2GqaxQoGxzqoIi-U1CLINow==
#           DOCKER_INFLUXDB_INIT_ORG: subjects
#           DOCKER_INFLUXDB_INIT_BUCKET: testUser
#         ports:
#           - 8086:8086
          
#       postgresintegrationtests:
#         image: postgres:latest
#         volumes:
#           - /lab01/fdserver/integrationTest/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
#         env:
#           POSTGRES_USER: admin
#           POSTGRES_PASSWORD: satanIsHere
#           POSTGRES_DB: users
#         ports:
#           - 5432:5432
    
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b
      - name: Run docker using make
        working-directory: ./lab01/fdserver/integrationTest
        run: make run
      - name: Run tests with gradle
        working-directory: ./lab01/fdserver
        run: sudo ./gradlew integrationTest --rerun-tasks --info
        
  runE2ETests:
    needs: runIntegrationTests
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b
      - name: Runs docker using make
        working-directory: ./lab01/fdserver/integrationTest
        run: make run
      - name: Run tests with gradle
        working-directory: ./lab01/fdserver
        run: sudo ./gradlew e2eTest --rerun-tasks --info -DnOfExecs=100
        
  runBDDTests:
    needs: runE2ETests
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b
      - name: Runs docker using make
        working-directory: ./lab01/fdserver/integrationTest
        run: make run
      - name: Run tests with gradle
        working-directory: ./lab01/fdserver
        run: sudo ./gradlew bddTest --rerun-tasks --info
